#pragma once

const char szBaseConfigFile[] =
	"<?xml version=\"1.0\"?>\n"
	"<XML>\n"
	"\t<SERVER>\n"
	"\t\t<IP>0,0,0,0</IP>\n"
	"\t\t<PORT>6000</PORT>\n"
	"\t</SERVER>\n"
	"\t<SKIN>Default</SKIN>\n"
	"\t<VIDEO>\n"
	"\t\t<WIDTH>1024</WIDTH>\n"
	"\t\t<HEIGHT>768</HEIGHT>\n"
	"\t\t<COLORBITS>32</COLORBITS>\n"
	"\t\t<GAMMA>213</GAMMA>\n"
	"\t\t<FULLSCREEN>TRUE</FULLSCREEN>\n"
	"\t\t<REFLECTION>true</REFLECTION>\n"
	"\t\t<LIGHTMAP>true</LIGHTMAP>\n"
	"\t\t<DYNAMICLIGHT>true</DYNAMICLIGHT>\n"
	"\t\t<SHADER>true</SHADER>\n"
	"\t\t<ANTIALIASING>2</ANTIALIASING>\n"
	"\t\t<CHARACTORTEXTURELEVEL>0</CHARACTORTEXTURELEVEL>\n"
	"\t\t<MAPTEXTURELEVEL>0</MAPTEXTURELEVEL>\n"
	"\t\t<EFFECTLEVEL>0</EFFECTLEVEL>\n"
	"\t\t<TEXTUREFORMAT>1</TEXTUREFORMAT>\n"
	"\t\t<MOVINGPICTURERESOLUTION>1</MOVINGPICTURERESOLUTION>\n"
	"\t\t<MOVINGPICTUREFILSIZE>0</MOVINGPICTUREFILSIZE>\n"
	"\t\t<NHARDWARETNL>false</NHARDWARETNL>\n"
	"\t</VIDEO>\n"
	"\t<AUDIO>\n"
	"\t\t<BGM_MUTE>false</BGM_MUTE>\n"
	"\t\t<BGM_VOLUME>0.166600</BGM_VOLUME>\n"
	"\t\t<EFFECT_MUTE>false</EFFECT_MUTE>\n"
	"\t\t<EFFECT_VOLUME>0.986200</EFFECT_VOLUME>\n"
	"\t\t<SOUND_3D>1</SOUND_3D>\n"
	"\t\t<A8BITSOUND>false</A8BITSOUND>\n"
	"\t\t<INVERSESOUND>false</INVERSESOUND>\n"
	"\t\t<HWMIXING>false</HWMIXING>\n"
	"\t\t<HITSOUND>true</HITSOUND>\n"
	"\t\t<NARRATIONSOUND>true</NARRATIONSOUND>\n"
	"\t</AUDIO>\n"
	"\t<MOUSE>\n"
	"\t\t<SENSITIVITY>1.000000</SENSITIVITY>\n"
	"\t\t<INVERT>FALSE</INVERT>\n"
	"\t</MOUSE>\n"
	"\t<JOYSTICK>\n"
	"\t\t<SENSITIVITY>1.000000</SENSITIVITY>\n"
	"\t\t<INVERT>FALSE</INVERT>\n"
	"\t</JOYSTICK>\n"
	"\t<KEYBOARD>\n"
	"\t\t<USEWEAPON alt=\"258\">29</USEWEAPON>\n"
	"\t\t<USEWEAPON2 alt=\"-1\">259</USEWEAPON2>\n"
	"\t\t<PREVOUSWEAPON alt=\"256\">16</PREVOUSWEAPON>\n"
	"\t\t<NEXTWEAPON alt=\"257\">18</NEXTWEAPON>\n"
	"\t\t<FORWARD alt=\"-1\">17</FORWARD>\n"
	"\t\t<BACK alt=\"-1\">31</BACK>\n"
	"\t\t<LEFT alt=\"-1\">30</LEFT>\n"
	"\t\t<RIGHT alt=\"-1\">32</RIGHT>\n"
	"\t\t<MELEEWEAPON alt=\"-1\">2</MELEEWEAPON>\n"
	"\t\t<PRIMARYWEAPON alt=\"-1\">3</PRIMARYWEAPON>\n"
	"\t\t<SECONDARYWEAPON alt=\"-1\">4</SECONDARYWEAPON>\n"
	"\t\t<ITEM1 alt=\"-1\">5</ITEM1>\n"
	"\t\t<ITEM2 alt=\"-1\">6</ITEM2>\n"
	"\t\t<COMMUNITYITEM1 alt=\"-1\">7</COMMUNITYITEM1>\n"
	"\t\t<COMMUNITYITEM2 alt=\"-1\">8</COMMUNITYITEM2>\n"
	"\t\t<RELOAD alt=\"-1\">19</RELOAD>\n"
	"\t\t<JUMP alt=\"-1\">57</JUMP>\n"
	"\t\t<SCORE alt=\"-1\">15</SCORE>\n"
	"\t\t<MENU alt=\"-1\">1</MENU>\n"
	"\t\t<TAUNT alt=\"-1\">41</TAUNT>\n"
	"\t\t<BOW alt=\"-1\">7</BOW>\n"
	"\t\t<WAVE alt=\"-1\">8</WAVE>\n"
	"\t\t<LAUGH alt=\"-1\">9</LAUGH>\n"
	"\t\t<CRY alt=\"-1\">10</CRY>\n"
	"\t\t<DANCE alt=\"-1\">11</DANCE>\n"
	"\t\t<SCREENSHOT alt=\"-1\">88</SCREENSHOT>\n"
	"\t\t<RECORD alt=\"-1\">87</RECORD>\n"
	"\t\t<MOVINGPICTURE alt=\"-1\">68</MOVINGPICTURE>\n"
	"\t\t<DEFENCE alt=\"-1\">42</DEFENCE>\n"
	"\t\t<TOGGLECHAT alt=\"-1\">47</TOGGLECHAT>\n"
	"\t\t<MOUSESENSITIVITYDEC alt=\"-1\">26</MOUSESENSITIVITYDEC>\n"
	"\t\t<MOUSESENSITIVITYINC alt=\"-1\">27</MOUSESENSITIVITYINC>\n"
	"\t</KEYBOARD>\n"
	"\t<MACRO>\n"
	"\t\t<F1></F1>\n"
	"\t\t<F2></F2>\n"
	"\t\t<F3></F3>\n"
	"\t\t<F4></F4>\n"
	"\t\t<F5></F5>\n"
	"\t\t<F6></F6>\n"
	"\t\t<F7></F7>\n"
	"\t\t<F8></F8>\n"
	"\t</MACRO>\n"
	"\t<ETC>\n"
	"\t\t<NETWORKPORT1>7700</NETWORKPORT1>\n"
	"\t\t<NETWORKPORT2>7800</NETWORKPORT2>\n"
	"\t\t<BOOST>FALSE</BOOST>\n"
	"\t\t<LANGUAGE>POR</LANGUAGE>\n"
	"\t\t<REJECT_NORMALCHAT>FALSE</REJECT_NORMALCHAT>\n"
	"\t\t<REJECT_TEAMCHAT>FALSE</REJECT_TEAMCHAT>\n"
	"\t\t<REJECT_CLANCHAT>FALSE</REJECT_CLANCHAT>\n"
	"\t\t<REJECT_WHISPER>FALSE</REJECT_WHISPER>\n"
	"\t\t<REJECT_INVITE>FALSE</REJECT_INVITE>\n"
	"\t\t<CROSSHAIR>1</CROSSHAIR>\n"
	"\t\t<FRAMELIMIT>1</FRAMELIMIT>\n"
	"\t</ETC>\n"
	"</XML>";